version: '3.8'
services:
  analytics_service:
    build: .
    ports:
      - "18080:8080"
    environment:
      ANALYTICS_DB_HOST: "analytics_db:5432"
    depends_on:
      - analytics_db

  analytics_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: analyticsdb
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
